[package]
name = "bluenine"
version = "0.1.0"
authors = ["Alvaro Mongil <hello@alvaromongil.com>"]

[lib]
name = "bluenine"
path = "src/lib.rs"

[dependencies]
clap = {version = "~2.19.0", features = ["yaml"]}
rusoto_core = "0.28.0"
rusoto_sts = "0.28.0"
rusoto_dynamodb = "0.28.0"